language: ruby
bundler_args: --without development
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby-18mode
  - jruby-19mode
  - jruby-20mode
  - jruby-21mode
  - jruby-head
  - rbx
  - ruby-head
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
  fast_finish: true
branches:
  only:
    - master
notifications:
  email: false
  campfire:
    on_success: never
    on_failure: never
    rooms:
      - secure: "AICTLi0MONccrRhoL8OjRugKDGvf5nWk1exKxKRPkYEN9LNLnk+2rUXxJpgr\n40k7D3zycQJyO9f5NXBeM8H9/2snBR6mKQLobjK1oVMxePzvA0uSKg2DbO80\njAfHsiSPPEO4/bLJBtw6h/LgTLt0wLdJVizLd213fm60m4Iw9wo="
    template:
      - "%{repository} (%{commit}) : %{message} %{foo} "
      - "Build details: %{build_url}"
